# Draw the tree illustrating the process generated by the count-change procedure
# of Section 1.2.2 in making change for 11 cents. What are the orders of growth
# of the space and number of steps used by this process as the amount to be
# changed increases?

# Recalling the procedure definition:
#
# (define (count-change amount) (cc amount 5))
# (define (cc amount kinds-of-coins)
#   (cond ((= amount 0) 1)
#     ((or (< amount 0) (= kinds-of-coins 0)) 0)
#     (else (+ (cc amount
#               (- kinds-of-coins 1))
#            (cc (- amount
#                 (first-denomination
#                   kinds-of-coins))
#              kinds-of-coins)))))
# (define (first-denomination kinds-of-coins)
#   (cond ((= kinds-of-coins 1) 1)
#     ((= kinds-of-coins 2) 5)
#     ((= kinds-of-coins 3) 10)
#     ((= kinds-of-coins 4) 25)
#     ((= kinds-of-coins 5) 50)))

library(DiagrammeR)
library(magrittr)

graph <- create_graph() %>% 
  add_node(label = "(count-change 11) -> (cc 11 5)") %>% 
  add_node(label = "(cc 11 4)", from = 1) %>% 
  add_node(label = "(cc -39 5) = 0", from = 1) %>% 
  add_node(label = "(cc 11 3)", from = 2) %>% 
  add_node(label = "(cc -14 4) = 0", from = 2) %>% 
  add_node(label = "(cc 11 2)", from = 4) %>% 
  add_node(label = "(cc 1 3)", from = 4) %>% 
  add_node(label = "(cc 11 1)", from = 6) %>% 
  add_node(label = "(cc 6 2)", from = 6) %>% 
  add_node(label = "(cc 1 2)", from = 7) %>% 
  add_node(label = "(cc -9 3) = 0", from = 7) %>% 
  add_node(label = "(cc 11 0) = 0", from = 8) %>% 
  add_node(label = "(cc 10 1)", from = 8) %>% 
  add_node(label = "(cc 6 1)", from = 9) %>% 
  add_node(label = "(cc 1 2)", from = 9) %>% 
  add_node(label = "(cc 1 1)", from = 10) %>% 
  add_node(label = "(cc -4 2) = 0", from = 10) %>% 
  add_node(label = "(cc 10 0) = 0", from = 13) %>% 
  add_node(label = "(cc 9 1)", from = 13) %>% 
  add_node(label = "(cc 6 0) = 0", from = 14) %>% 
  add_node(label = "(cc 5 1)", from = 14) %>% 
  add_node(label = "(cc 1 1)", from = 15) %>% 
  add_node(label = "(cc -4 2) = 0", from = 15) %>% 
  add_node(label = "(cc 1 0) = 0", from = 16) %>% 
  add_node(label = "(cc 0 1) = 1", from = 16) %>% 
  add_node(label = "(cc 9 0) = 0", from = 19) %>% 
  add_node(label = "(cc 8 1)", from = 19) %>% 
  add_node(label = "(cc 5 0) = 0", from = 21) %>% 
  add_node(label = "(cc 4 1)", from = 21) %>% 
  add_node(label = "(cc 1 0) = 0", from = 22) %>% 
  add_node(label = "(cc 0 1) = 1", from = 22) %>% 
  add_node(label = "(cc 8 0) = 0", from = 27) %>% 
  add_node(label = "(cc 7 1)", from = 27) %>% 
  add_node(label = "(cc 4 0) = 0", from = 29) %>% 
  add_node(label = "(cc 3 1)", from = 29) %>% 
  add_node(label = "(cc 7 0) = 0", from = 33) %>% 
  add_node(label = "(cc 6 1)", from = 33) %>% 
  add_node(label = "(cc 3 0) = 0", from = 35) %>% 
  add_node(label = "(cc 2 1)", from = 35) %>% 
  add_node(label = "(cc 6 0) = 0", from = 37) %>% 
  add_node(label = "(cc 5 1)", from = 37) %>% 
  add_node(label = "(cc 2 0) = 0", from = 39) %>% 
  add_node(label = "(cc 1 1)", from = 39) %>% 
  add_node(label = "(cc 5 0) = 0", from = 41) %>% 
  add_node(label = "(cc 4 1)", from = 41) %>% 
  add_node(label = "(cc 1 0) = 0", from = 43) %>% 
  add_node(label = "(cc 0 1) = 1", from = 43) %>% 
  add_node(label = "(cc 4 0) = 0", from = 45) %>% 
  add_node(label = "(cc 3 1)", from = 45) %>% 
  add_node(label = "(cc 3 0) = 0", from = 49) %>% 
  add_node(label = "(cc 2 1)", from = 49) %>% 
  add_node(label = "(cc 2 0) = 0", from = 51) %>% 
  add_node(label = "(cc 1 1)", from = 51) %>% 
  add_node(label = "(cc 1 0) = 0", from = 53) %>% 
  add_node(label = "(cc 0 1) = 1", from = 53)

render_graph(graph, layout = "tree")

# DiagrammeR is not working alright after a few levels, not sure why, but that's
# the idea...
#
# Order of growth of space:
# The evaluation tree rapidly approaches the case in which the change is
# computed with just a single type of coin. In this case, and assuming that the
# lowest-value coin is worth 1, the procedure recursively subtract 1 from n
# until it reaches 0. We can see, then, that the depth of this tree is
# approximately n (a few interactions before arriving at (cc n 1), then n levels
# until it reaches the bottom of the tree), so the order of growth of space is 
# O(n).
#
# Order of growth of number of steps:
# t = number types of coins
#
# t = 1
# total nodes: 2*n + 1
#
# t = 2
# be k = n/5
# the tree will have a big subtree which is (cc n 1), total cells = 2n
# to the other side it, k subtrees: are (cc n-5 2) (cc n-10 2) .. (cc n-5*k 2)
# each one of these with another subtree spawning from it: (cc n-5*k 1)
# order-of-growth ~ (k)*(2n) ~ (n/5)*(2n) ~ n^2
#
# t = 3
# now let k = n/10
# this time the tree will separate into a big subtree (cc n 2) and k subtrees
# (cc n-10 3) .. (cc n-10*k 3). each one of these also spawns a subtree
# (cc n-10*k 2).
# so order-of-growth ~ (k)*(n^2) ~ (n/10)*(n^2) ~ n^3
#
# this pattern keeps occurring, so when we have t=5 like in the example above
# we have O(n^5)
#
# ps: if n is smaller than the value that effectively "unlocks" a certain coin, 
# the procedure will behave more or less like if the number of coins is
# restricted. so, for example, for n=1 to n=4 the order of growth will be O(n).
# but since the order of growth is a measure more relevant to large numbers,
# let's assume that n>=50.
